// expensesOptions.js
export const expenseTypesOptions = [
  { value: 'Renovation', label: 'Renovation', color: '#1985d7ff' },
  { value: 'Equipment', label: 'Equipment', color: '#1985d7ff' },
  { value: 'Delivery Vehicle', label: 'Delivery Vehicle', color: '#1985d7ff' },
  { value: 'Permits', label: 'Permits', color: '#1985d7ff' },
  { value: 'Store Equipment', label: 'Store Equipment', color: '#1985d7ff' },
  { value: 'Dispenser', label: 'Dispenser', color: '#1985d7ff' },
  { value: 'Containers', label: 'Containers', color: '#1985d7ff' },
  { value: 'Security Deposit', label: 'Security Deposit', color: '#1985d7ff' },
  { value: 'Consumables', label: 'Consumables', color: '#1985d7ff' },
  { value: 'Rent', label: 'Rent', color: '#ff5255ff' },
  { value: 'Electric Bill', label: 'Electric Bill', color: '#ff5255ff' },
  { value: 'Water Bill', label: 'Water Bill', color: '#ff5255ff' },
  { value: 'Gas', label: 'Gas', color: '#ff5255ff' },
  { value: 'Water Analysis', label: 'Water Analysis', color: '#ff5255ff' },
  { value: 'Miscellaneous', label: 'Miscellaneous', color: '#ff5255ff' },
  { value: 'Transportation', label: 'Transportation', color: '#ff5255ff' },
  { value: 'Penalties', label: 'Penalties', color: '#ff5255ff' },
  { value: 'Maintenance', label: 'Maintenance', color: '#ff5255ff' },
  { value: 'Employee - Salary', label: 'Employee - Salary', color: '#efd332ff' },
  { value: 'Employee - Commission', label: 'Employee - Commission', color: '#efd332ff' },
  { value: 'Employee - Cash Advance', label: 'Employee - Cash Advance', color: '#efd332ff' },
  { value: 'Employee - Deductions', label: 'Employee - Deductions', color: '#efd332ff' },
  { value: 'Employee - Benefits', label: 'Employee - Benefits', color: '#efd332ff' },
  { value: 'Sellables - Bottles', label: 'Sellables - Bottles', color: '#c030c8ff' },
  { value: 'Sellables - Containers', label: 'Sellables - Containers', color: '#c030c8ff' },
  { value: 'Sellables - Packaging Materials', label: 'Sellables - Packaging Materials', color: '#c030c8ff' },
  { value: 'Sellables - Caps', label: 'Sellables - Caps', color: '#c030c8ff' },
];
